; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; -------------------------------------------------------------------------
; Configurações Globais (Aplicam-se a todos os ambientes, a menos que sejam substituídas)
; -------------------------------------------------------------------------
[env]
platform = espressif32
framework = arduino
monitor_speed = 115200

; -------------------------------------------------------------------------
; 1. MASTER (ESP32 DevKit + INA219)
; -------------------------------------------------------------------------
[env:master]
board = esp32dev
board_build.filesystem = littlefs
lib_deps = 
    robtillaart/INA226 @ ^0.5.5
; Ignora tudo em src/ e compila APENAS a pasta src/master/
build_src_filter = -<*> +<master/>

; -------------------------------------------------------------------------
; 2. MINI (ESP32-C3 Super Mini + INA226)
; -------------------------------------------------------------------------
[env:slave-1-cidade]
board = esp32-c3-devkitm-1
board_build.mcu = esp32c3
board_build.f_cpu = 160000000L
lib_deps = 
    robtillaart/INA226 @ ^0.5.5
; Ignora tudo em src/ e compila APENAS a pasta src/slave-1-cidade/
build_src_filter = -<*> +<slave-1-cidade/>
; DEBUG
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

[env:slave-2-fonte]
board = esp32-c3-devkitm-1
board_build.mcu = esp32c3
board_build.f_cpu = 160000000L
lib_deps = 
    adafruit/Adafruit INA219@^1.2.3
; Ignora tudo em src/ e compila APENAS a pasta src/slave-2-fonte/
build_src_filter = -<*> +<slave-2-fonte/>
; DEBUG
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

[env:slave-3-peso]
board = esp32dev                 
board_build.filesystem = littlefs
build_src_filter = -<*> +<slave-3-peso/>